name: 'GitOps Manager'
description: 'The GitOps Manager Utility'
branding:
  icon: box
  color: blue
inputs:
  command:
    description: 'Command'
    required: true
  owner:
    description: 'Github username'
    required: true
  repository:
    description: 'Github repository name'
    required: true
  mergeRequestId:
    description: 'Github current merge request identifier'
    required: true
  bypass:
    description: 'bypass of execution of command'
    required: false
    default: 'NO'
  gbtoken:
    description: 'Github your personal access token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
#  using: 'composite'
#  steps:
#    - run: ./scripts/executable
#      shell: bash