on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: mdnbras/check-semantic-version-action@v1
      with:
        command: 'commits-verify'
        owner: 'mdnbras'
        repository: 'check-semantic-version-action'
        mergeRequestId: 3
        gbtoken: ${{ secrets.PA_TOKEN }}
        bypass: 'NO'
        urlWebhook: ${{ secrets.DISCORD_WEBHOOK }}

#    - name: Echo
#      run: echo ${PWD}
#
#    - name: List
#      run: ls -la
#
#    - name: Execute Success
#      continue-on-error: true
#      run: ${PWD}/scripts/executable verify -versionOld v0.0.1 -versionNew v0.0.2
#
#    - name: Execute Failed
#      continue-on-error: true
#      run: ${PWD}/scripts/executable verify -versionOld v0.4.2 -versionNew v0.4.1
