on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Echo
      run: echo ${PWD}

    - name: Execute
      run: ${PWD}/scripts/executable verify -versionOld v0.0.1 -versionNew v0.0.2

    - name: List
      run: ls -la